/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableAnalysis

/-!
# Axiom audit

Checks that the library depends only on the standard axioms `propext`,
`Classical.choice`, and `Quot.sound`. Run via
`lake env lean scripts/AxiomAudit.lean` (done by `scripts/check.sh`); any
disallowed axiom is a hard error.

Two layers:

* **Environment sweep**: every declaration whose *owning module* is `ComputableAnalysis`
  or a submodule is checked — including `private` declarations (whose mangled
  `_private.*` names defeat any namespace-prefix filter) and compiler-generated
  auxiliaries — so a `native_decide`/`ofReduceBool` (or any custom axiom) anywhere in
  the library fails the gate, whether or not the declaration is listed below.
* **Headline regression list**: `headlineDecls` is extended in every unit; because the
  double-backtick names resolve at elaboration, a deletion or rename of a headline
  declaration also fails the gate. The list targets proof declarations and named
  instances, not `structure` types (auditing a structure declaration is vacuous).
-/

open Lean

def allowedAxioms : List Name := [``propext, ``Classical.choice, ``Quot.sound]

/-- Headline declarations to audit; extended with each unit. -/
def headlineDecls : List Name :=
  [-- Unit 1: Baire/Cantor finite-observation layer
   ``ComputableAnalysis.isClopen_cylinder,
   ``ComputableAnalysis.cylinder_streamTake,
   ``ComputableAnalysis.primrec_isPrefix,
   ``ComputableAnalysis.Baire.ofList_streamTake,
   ``ComputableAnalysis.lt_prefixBound_of_mem,
   ``ComputableAnalysis.primrec_prefixBound,
   ``ComputableAnalysis.primrec_boolWordToNat,
   ``ComputableAnalysis.primrec_natWordToBool,
   -- Unit 2: oracle-code syntax and evaluator
   ``ComputableAnalysis.OracleCode.instDenumerable,
   ``ComputableAnalysis.OracleCode.primrec₂_pair,
   ``ComputableAnalysis.OracleCode.primrec₂_comp,
   ``ComputableAnalysis.OracleCode.primrec₂_prec,
   ``ComputableAnalysis.OracleCode.primrec_rfind',
   ``ComputableAnalysis.OracleCode.primrec_const,
   ``ComputableAnalysis.OracleCode.primrec₂_curry,
   ``ComputableAnalysis.OracleCode.eval_query,
   ``ComputableAnalysis.OracleCode.eval_rfind,
   ``ComputableAnalysis.OracleCode.eval_ofPartrecCode,
   -- Unit 3: bounded simulation
   ``ComputableAnalysis.OracleCode.primrec_recOn,
   ``ComputableAnalysis.OracleCode.evalnPrefix_bound,
   ``ComputableAnalysis.OracleCode.evalnPrefix_mono,
   ``ComputableAnalysis.OracleCode.evalnPrefix_sound,
   ``ComputableAnalysis.OracleCode.evalnPrefix_complete,
   ``ComputableAnalysis.OracleCode.evaln_sound,
   ``ComputableAnalysis.OracleCode.evaln_complete,
   ``ComputableAnalysis.OracleCode.primrec_evalnPrefix,
   ``ComputableAnalysis.OracleCode.computable_evalnPrefix,
   -- Unit 4: universal evaluator, s-m-n, fixed-oracle RecursiveIn
   ``ComputableAnalysis.OracleCode.smn,
   ``ComputableAnalysis.OracleCode.eval_comp_eq,
   ``ComputableAnalysis.OracleCode.exists_code_iff_recursiveIn,
   ``ComputableAnalysis.OracleCode.exists_universal,
   -- Unit 5: finite use, continuity, stream layer
   ``ComputableAnalysis.OracleCode.eval_eq_of_agree_on_use,
   ``ComputableAnalysis.type2Computable_continuous,
   ``ComputableAnalysis.type2Computable_truncate,
   ``ComputableAnalysis.not_type2Computable_notAllZero,
   -- Unit 5 (stream closure API): composition, pairing, projections, stream-view link
   ``ComputableAnalysis.OracleCode.eval_subst,
   ``ComputableAnalysis.OracleCode.computes_iff_evalStream,
   ``ComputableAnalysis.Type2Computable.comp,
   ``ComputableAnalysis.Type2Computable.interleave,
   ``ComputableAnalysis.type2Computable_evenPart,
   ``ComputableAnalysis.type2Computable_oddPart,
   -- Unit 5 (API hardening): pointwise partial-realizer interface + reusable pairing
   ``ComputableAnalysis.OracleCode.mem_evalStream,
   ``ComputableAnalysis.OracleCode.eval_subst_of_eval,
   ``ComputableAnalysis.OracleCode.evalStream_subst,
   ``ComputableAnalysis.OracleCode.exists_pairStreams,
   ``ComputableAnalysis.OracleCode.pairCode_spec,
   ``ComputableAnalysis.type2Computable_const_stream,
   ``ComputableAnalysis.Baire.evenPart_interleave,
   ``ComputableAnalysis.Baire.oddPart_interleave,
   -- Unit 6: effective compactness (uniform prefix table)
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_partrec,
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_dom,
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_nodup,
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_length,
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_disjoint,
   ``ComputableAnalysis.OracleCode.uniformPrefixTableSearch_preimage,
   -- Unit 7: representations + computable points
   ``ComputableAnalysis.Representation.valid_iff_exists_names,
   ``ComputableAnalysis.Representation.names_unique,
   ``ComputableAnalysis.baireRep,
   ``ComputableAnalysis.cantorRep,
   ``ComputableAnalysis.natRep,
   ``ComputableAnalysis.discreteRep,
   -- Unit 8: realizers + computable maps
   ``ComputableAnalysis.OracleCode.computable_of_mem_evalStream,
   ``ComputableAnalysis.ComputableMap.id,
   ``ComputableAnalysis.ComputableMap.comp,
   ``ComputableAnalysis.ComputableMap.computablePoint,
   ``ComputableAnalysis.ComputableMap.pair,
   ``ComputableAnalysis.Representation.prod,
   ``ComputableAnalysis.Representation.sum,
   ``ComputableAnalysis.Representation.subtype,
   ``ComputableAnalysis.computableMap_fst,
   ``ComputableAnalysis.computableMap_snd,
   ``ComputableAnalysis.computableMap_inl,
   ``ComputableAnalysis.computableMap_inr,
   ``ComputableAnalysis.computableMap_subtypeVal,
   ``ComputableAnalysis.computableMap_encodeCantor,
   -- Unit 9: representation equivalence
   ``ComputableAnalysis.Representation.Equiv.refl,
   ``ComputableAnalysis.Representation.Equiv.symm,
   ``ComputableAnalysis.Representation.Equiv.trans,
   ``ComputableAnalysis.Representation.Equiv.computableMap_congr,
   ``ComputableAnalysis.Representation.Equiv.computablePoint_congr,
   ``ComputableAnalysis.cantorRepRedundant,
   ``ComputableAnalysis.cantorRep_equiv_redundant,
   -- Unit 10: problems + ordinary Weihrauch reduction
   ``ComputableAnalysis.Problem.exists_realizer,
   ``ComputableAnalysis.Problem.exists_realizer_patch,
   ``ComputableAnalysis.Problem.Equivalent.realizes_iff,
   ``ComputableAnalysis.reduction_iff_exists_reductionPair,
   ``ComputableAnalysis.WeihrauchReducible.refl,
   ``ComputableAnalysis.WeihrauchReducible.trans,
   ``ComputableAnalysis.WeihrauchReducible.congr,
   ``ComputableAnalysis.computableProblem_iff_le_idProblem,
   ``ComputableAnalysis.idProblem,
   ``ComputableAnalysis.zeroProblem,
   ``ComputableAnalysis.constNatZeroProblem,
   ``ComputableAnalysis.constZeroProblem,
   -- Unit 11: strong reduction + the ≤W/≤sW separation
   ``ComputableAnalysis.strongReduction_iff_exists_reductionPair,
   ``ComputableAnalysis.strongWeihrauch_le_weihrauch,
   ``ComputableAnalysis.StrongWeihrauchReducible.refl,
   ``ComputableAnalysis.StrongWeihrauchReducible.trans,
   ``ComputableAnalysis.StrongWeihrauchReducible.congr,
   ``ComputableAnalysis.idProblem_le_constZero,
   ``ComputableAnalysis.idProblem_not_sle_constZero,
   ``ComputableAnalysis.exists_reduction_not_strong,
   -- Unit 18: Cantor measurable structure + cylinder masses
   ``ComputableAnalysis.measurableSet_cylinder,
   ``ComputableAnalysis.isPiSystem_cantorCylinders,
   ``ComputableAnalysis.generateFrom_cantorCylinders,
   ``ComputableAnalysis.cylMass,
   ``ComputableAnalysis.cylMass_split,
   ``ComputableAnalysis.cylMass_isConsistent,
   ``ComputableAnalysis.cylMass_injective,
   -- Unit 19: existence from consistent masses (route B, Ionescu–Tulcea)
   ``ComputableAnalysis.existsUnique_probabilityMeasure_of_isConsistent,
   -- Unit 14: coded rationals + computable metric presentations + Type-2 riders
   ``ComputableAnalysis.OracleCode.exists_snocCode,
   ``ComputableAnalysis.OracleCode.exists_takeCode,
   ``ComputableAnalysis.OracleCode.exists_ofNatFnCode,
   ``ComputableAnalysis.OracleCode.exists_prefixPostCode,
   ``ComputableAnalysis.OracleCode.eval_comp_some,
   ``ComputableAnalysis.OracleCode.eval_pair_some,
   ``ComputableAnalysis.ratOfCode_surjective,
   -- Unit 15: the fast Cauchy representation
   ``ComputableAnalysis.ComputableMetricPresentation.namesPoint_unique,
   ``ComputableAnalysis.ComputableMetricPresentation.cauchyRep,
   ``ComputableAnalysis.ComputableMetricPresentation.cauchyRep_names_iff,
   ``ComputableAnalysis.ComputableMetricPresentation.IsFastCauchy.exists_namesPoint,
   ``ComputableAnalysis.ComputableMetricPresentation.IsFastCauchy.valid,
   -- Unit 16: represented reals + [0,1] arithmetic contract
   ``ComputableAnalysis.rationalPresentation,
   ``ComputableAnalysis.realPresentation,
   ``ComputableAnalysis.realRep,
   ``ComputableAnalysis.unitIntervalRep,
   ``ComputableAnalysis.computablePoint_realZero,
   ``ComputableAnalysis.computablePoint_realOne,
   ``ComputableAnalysis.computableMap_realAdd,
   ``ComputableAnalysis.computableMap_realNeg,
   ``ComputableAnalysis.computableMap_realMul,
   ``ComputableAnalysis.computableMap_realDist,
   ``ComputableAnalysis.computableMap_unitSymm,
   ``ComputableAnalysis.exists_uniform_sum_realizer,
   ``ComputableAnalysis.exists_uniform_unitProd_realizer,
   -- Unit 20: the Cantor computable-measure representation
   ``ComputableAnalysis.measureNames_unique,
   ``ComputableAnalysis.cantorMeasureRep,
   ``ComputableAnalysis.cantorMeasureRep_names_iff,
   ``ComputableAnalysis.cantorMeasureSpace,
   -- Unit 21: uniform cylinder-value equivalence
   ``ComputableAnalysis.computablePoint_cantorMeasureRep_iff,
   -- Unit 22: measure constructors
   ``ComputableAnalysis.Cantor.interleave_mem_cylinder_iff,
   ``ComputableAnalysis.Cantor.measurable_interleave,
   ``ComputableAnalysis.diracMeasure,
   ``ComputableAnalysis.cylMass_diracMeasure,
   ``ComputableAnalysis.computablePoint_diracMeasure,
   ``ComputableAnalysis.bernoulliProduct,
   ``ComputableAnalysis.cylMass_bernoulliProduct,
   ``ComputableAnalysis.computableMap_bernoulliProduct,
   ``ComputableAnalysis.finiteMixture,
   ``ComputableAnalysis.cylMass_finiteMixture,
   ``ComputableAnalysis.exists_uniform_finiteMixture_realizer,
   ``ComputableAnalysis.productMeasure,
   ``ComputableAnalysis.cylMass_productMeasure,
   ``ComputableAnalysis.productMeasure_eq_map_prod,
   ``ComputableAnalysis.computableMap_productMeasure,
   -- Unit 23: pushforward
   ``ComputableAnalysis.continuous_of_computableMap_cantor,
   ``ComputableAnalysis.measurable_of_computableMap_cantor,
   ``ComputableAnalysis.pushforwardMeasure,
   ``ComputableAnalysis.exists_pushforward_cylinder_table,
   ``ComputableAnalysis.computableMap_pushforwardMeasure,
   ``ComputableAnalysis.pushforwardMeasure_comp,
   -- Unit 12: LPO, LLPO, and the multivalued-oracle test
   ``ComputableAnalysis.LPO,
   ``ComputableAnalysis.LPO.dom_total,
   ``ComputableAnalysis.not_computableProblem_LPO,
   ``ComputableAnalysis.LLPO,
   ``ComputableAnalysis.llpoSwap,
   ``ComputableAnalysis.llpo_le_lpo,
   ``ComputableAnalysis.llpo_swap_le_llpo,
   ``ComputableAnalysis.llpo_accepts_zero_both,
   -- Unit 13: the limit operator
   ``ComputableAnalysis.Lim,
   ``ComputableAnalysis.Lim.accepts_unique,
   ``ComputableAnalysis.lpo_le_lim,
   -- Unit 24: the Cantor metric presentation (unit 17 slice) + the threshold builder
   ``ComputableAnalysis.repred_of_ratLt,
   ``ComputableAnalysis.cantorPresentation,
   ``ComputableAnalysis.cantorPresentation_cauchyRep_equiv,
   -- Unit 25: represented advice-realizable maps + the stream-level universal evaluator
   ``ComputableAnalysis.OracleCode.exists_advisedEvalCode,
   ``ComputableAnalysis.advisedRealizes_unique,
   ``ComputableAnalysis.RealizableFun.ext,
   ``ComputableAnalysis.funRep,
   ``ComputableAnalysis.funRep_names_iff,
   ``ComputableAnalysis.computableMap_funRep_eval,
   ``ComputableAnalysis.RealizableFun.computablePoint_const,
   ``ComputableAnalysis.computableMap_funRep_postcomp,
   -- Unit 26: REPred closure riders + the prefix-chain bridge
   ``ComputableAnalysis.repred_comp,
   ``ComputableAnalysis.repred_of_primrecPred,
   ``ComputableAnalysis.repred_and,
   ``ComputableAnalysis.repred_or,
   ``ComputableAnalysis.repred_exists_nat,
   ``ComputableAnalysis.repred_forall_lt,
   ``ComputableAnalysis.repred_exists_lt,
   ``ComputableAnalysis.OracleCode.exists_prefixChainCode,
   -- Unit 27: generic Prokhorov presentation + the weak measure representation
   ``ComputableAnalysis.exists_atomic_close,
   ``ComputableAnalysis.weakMeasureRep,
   ``ComputableAnalysis.weakMeasureRep_names_iff,
   ``ComputableAnalysis.prokhorovPresentation,
   -- Unit 28: the Cantor/weak measure-representation equivalence
   ``ComputableAnalysis.cantorMeasureRep_equiv_weak,
   -- Unit 29: Cauchy admissibility
   ``ComputableAnalysis.continuous_advisedRealizable,
   -- Unit 30: the continuous Markov kernel carrier
   ``ComputableAnalysis.ContinuousMarkovKernel.toKernel,
   ``ComputableAnalysis.ContinuousMarkovKernel.advisedRealizable,
   ``ComputableAnalysis.ContinuousMarkovKernel.toRealizableFun,
   ``ComputableAnalysis.ContinuousMarkovKernel.ofRealizableFun,
   -- Unit 31: bounded-Lipschitz integration
   ``ComputableAnalysis.BoundedLipschitzFun.ext,
   ``ComputableAnalysis.blRep,
   ``ComputableAnalysis.blRep_names_iff,
   ``ComputableAnalysis.computableMap_integrateBL,
   ``ComputableAnalysis.exists_boundedLipschitzFamilyIntegration_realizer,
   -- Unit 32: the shared conditioning layer
   ``ComputableAnalysis.ComputableMetricPresentation.prod,
   ``ComputableAnalysis.ComputableMetricPresentation.separableSpace,
   ``ComputableAnalysis.ComputableMetricPresentation.borelSpace_prod,
   ``ComputableAnalysis.StrongWeihrauchEquivalent,
   ``ComputableAnalysis.funRep_computablePoint_iff,
   ``ComputableAnalysis.isCondKernel_ae_unique,
   ``ComputableAnalysis.Condition,
   ``ComputableAnalysis.inducedKernel,
   ``ComputableAnalysis.continuousKernelEquiv,
   ``ComputableAnalysis.FullFirstMarginalSupport.isOpenPosMeasure,
   ``ComputableAnalysis.Disintegrate,
   ``ComputableAnalysis.disintegrate_dom_iff,
   ``ComputableAnalysis.disintegrate_accepts_unique,
   -- Unit 33: division away from zero + funRep currying
   ``ComputableAnalysis.computableMap_realInv_pos,
   ``ComputableAnalysis.computableMap_funRep_curry,
   ``ComputableAnalysis.RealizableFun.computablePoint_curry,
   -- Unit 34: converse admissibility + Cantor standard-Borel + fair-coin full support
   ``ComputableAnalysis.continuous_of_advisedRealizes,
   ``ComputableAnalysis.RealizableFun.continuous_toFun_of_cauchy,
   ``ComputableAnalysis.PiNatInstances.polishSpace_cantor,
   ``ComputableAnalysis.PiNatInstances.standardBorelSpace_cantor,
   ``ComputableAnalysis.isOpenPosMeasure_bernoulliProduct,
   ``ComputableAnalysis.support_bernoulliProduct,
   -- Unit 35: the deinterleave pushforward and its computability bridge
   ``ComputableAnalysis.cantorDeinterleave_preimage_prod,
   ``ComputableAnalysis.jointOfCantor,
   ``ComputableAnalysis.jointOfCantor_apply_prod,
   ``ComputableAnalysis.jointOfCantor_rectangle,
   ``ComputableAnalysis.computableMap_jointOfCantor,
   -- Unit 36 (Part A): noncomputability of conditional probability
   ``ComputableAnalysis.condition_noncomputable,
   -- Unit 37 (Part B): the bounded-Lipschitz everywhere-positive specialization
   ``ComputableAnalysis.isCondKernel_bayesKernel,
   ``ComputableAnalysis.computableMap_reweight,
   ``ComputableAnalysis.computableMap_bayesCond,
   ``ComputableAnalysis.computableMap_bayesCond_curried,
   -- Unit 38: the head-cons function-space name emitter
   ``ComputableAnalysis.funPack,
   ``ComputableAnalysis.funCode_funPack,
   ``ComputableAnalysis.funAdvice_funPack,
   ``ComputableAnalysis.names_funPack,
   ``ComputableAnalysis.exists_funPackCode,
   -- Unit 39: the reduce-to-Lim input/jump table
   ``ComputableAnalysis.jumpBit,
   ``ComputableAnalysis.jumpBit_cases,
   ``ComputableAnalysis.jumpBit_mono,
   ``ComputableAnalysis.limTable,
   ``ComputableAnalysis.limTable_dom,
   ``ComputableAnalysis.exists_limTableCode,
   -- Unit 40: the Cantor Dirac decoder (and the coded-comparison builder it needs)
   ``ComputableAnalysis.primrecPred_ratLt,
   ``ComputableAnalysis.exists_diracDecodeCode,
   -- Unit 41 (Part C1, lower half): the calibration lower bound
   ``ComputableAnalysis.lim_le_disintegrate,
   -- Shared Primrec arithmetic (issue #6 consolidation): fixed-base exponentiation
   ``ComputableAnalysis.primrec_pow,
   -- Parameter-uniform Primrec list combinators (issue #17)
   ``ComputableAnalysis.primrec_list_filter,
   ``ComputableAnalysis.primrec_list_all,
   ``ComputableAnalysis.primrec_list_any,
   ``ComputableAnalysis.primrec_list_sum,
   -- Staged approximation of r.e. predicates (issue #21)
   ``ComputableAnalysis.repred_exists_primrec_stages,
   ``ComputableAnalysis.repred_exists_primrec_cumulative,
   ``ComputableAnalysis.exists_common_stage_of_persistent,
   -- Bundled Weihrauch reduction witnesses
   ``ComputableAnalysis.weihrauchReducible_iff_nonempty,
   ``ComputableAnalysis.strongWeihrauchReducible_iff_nonempty,
   -- The executable reduction-witness calculus (issue #26)
   ``ComputableAnalysis.OracleCode.evalStream_evenCode,
   ``ComputableAnalysis.OracleCode.evalStream_oddCode,
   ``ComputableAnalysis.isReductionPair_refl,
   ``ComputableAnalysis.IsReductionPair.comp,
   ``ComputableAnalysis.IsReductionPair.congr,
   ``ComputableAnalysis.isStrongReductionPair_refl,
   ``ComputableAnalysis.IsStrongReductionPair.comp,
   ``ComputableAnalysis.IsStrongReductionPair.toReductionPair,
   ``ComputableAnalysis.IsStrongReductionPair.congr,
   ``ComputableAnalysis.WeihrauchReduction.trans_pre,
   ``ComputableAnalysis.WeihrauchReduction.trans_post,
   ``ComputableAnalysis.StrongWeihrauchReduction.trans_pre,
   ``ComputableAnalysis.StrongWeihrauchReduction.trans_post,
   ``ComputableAnalysis.StrongWeihrauchReduction.toWeihrauch_post,
   -- Track packing and the generic trackwise map (issue #27)
   ``ComputableAnalysis.OracleCode.mapTracks,
   ``ComputableAnalysis.OracleCode.eval_mapTracks_pair,
   ``ComputableAnalysis.OracleCode.evalStream_mapTracks_iff,
   ``ComputableAnalysis.OracleCode.eval_addCode,
   ``ComputableAnalysis.OracleCode.eval_div2mod2Code,
   ``ComputableAnalysis.OracleCode.evalStream_repeatTracksCode,
   ``ComputableAnalysis.OracleCode.evalStream_extractTrackCode,
   ``ComputableAnalysis.OracleCode.evalStream_zipTracksCode,
   ``ComputableAnalysis.OracleCode.evalStream_unzipTracksCode,
   ``ComputableAnalysis.OracleCode.evalStream_flattenTracksCode,
   ``ComputableAnalysis.OracleCode.evalStream_unflattenTracksCode,
   -- The countable-product representation (issue #27)
   ``ComputableAnalysis.Representation.sequence_names_iff,
   ``ComputableAnalysis.RepSpace.sequence,
   ``ComputableAnalysis.Representation.computableMap_const_sequence,
   ``ComputableAnalysis.Representation.computableMap_apply_sequence,
   ``ComputableAnalysis.Representation.computableMap_sequence_prod,
   ``ComputableAnalysis.Representation.computableMap_prod_sequence,
   ``ComputableAnalysis.Representation.computableMap_sequence_flatten,
   ``ComputableAnalysis.Representation.computableMap_sequence_unflatten,
   -- Bernoulli product as an infinite product measure (classical API)
   ``ComputableAnalysis.cylinder_eq_pi,
   ``ComputableAnalysis.measurableSet_cylinderCoord,
   ``ComputableAnalysis.bernoulliMeasure_cylinderCoord,
   ``ComputableAnalysis.bernoulliProduct_toMeasure,
   ``ComputableAnalysis.measurable_bernoulliProduct_toMeasure,
   ``ComputableAnalysis.cylMass_bernoulliProduct_eq_pow,
   -- The computable metric presentation of [0,1]
   ``ComputableAnalysis.clamp_mem_Icc,
   ``ComputableAnalysis.clamp_eq_self,
   ``ComputableAnalysis.abs_clamp_sub_clamp_le,
   ``ComputableAnalysis.unitIntervalPresentation,
   ``ComputableAnalysis.unitIntervalMeasureRep,
   ``ComputableAnalysis.unitIntervalPresentation_cauchyRep_equiv,
   -- Moments on the unit interval: foundations and determinacy
   ``ComputableAnalysis.moment_mem_unitInterval,
   ``ComputableAnalysis.moment_zero,
   ``ComputableAnalysis.isCompletelyMonotone_moment,
   ``ComputableAnalysis.eq_of_forall_moment_eq,
   ``ComputableAnalysis.moment_injective,
   -- The moment-sequence representation
   ``ComputableAnalysis.momentNames_unique,
   ``ComputableAnalysis.hausdorffMomentRep,
   ``ComputableAnalysis.hausdorffMomentRep_names_iff,
   -- Rider: certified weights under-estimate the atomic mass (unit 42 prerequisite)
   ``ComputableAnalysis.exists_certifiedWeightCode,
   -- Rider: the certified-weight accumulator that is exact on complete masks
   ``ComputableAnalysis.exists_completeCertifiedWeightCode,
   -- Rider: the least-witness prefix search builder, promoted on its second consumer
   ``ComputableAnalysis.OracleCode.exists_prefixSearchCode,
   -- Rider: computable problems return computable answers; conditioning is not computable
   ``ComputableAnalysis.ComputableProblem.exists_computablePoint_accepts,
   ``ComputableAnalysis.not_computableProblem_condition,
   -- Rational codes: coded naturals and coded positive fractions
   ``ComputableAnalysis.ratOfCode_natCode,
   ``ComputableAnalysis.primrec_natCode,
   ``ComputableAnalysis.ratOfCode_fracCode,
   ``ComputableAnalysis.primrec₂_fracCode,
   -- The same-atoms Lévy–Prokhorov perturbation bound
   ``ComputableAnalysis.levyProkhorovDist_le_sum_abs,
   -- The binomial approximant of a measure on the unit interval
   ``ComputableAnalysis.binomialWeight_nonneg,
   ``ComputableAnalysis.sum_binomialWeight,
   ``ComputableAnalysis.binomialApproximant,
   ``ComputableAnalysis.binomialApproximant_toMeasure,
   ``ComputableAnalysis.sum_bernstein_far_le,
   ``ComputableAnalysis.sum_bernstein_far_le_dyadic,
   ``ComputableAnalysis.levyProkhorovDist_binomialApproximant_le,
   -- From approximate moments to a probability vector of binomial weights
   ``ComputableAnalysis.binomialWeight_eq_moment_sum,
   ``ComputableAnalysis.binomialWeight_le_one,
   ``ComputableAnalysis.sum_choose_mul_two_pow,
   ``ComputableAnalysis.sum_abs_approxWeight_sub_le,
   ``ComputableAnalysis.sum_abs_clipWeight_sub_le,
   ``ComputableAnalysis.totalClipWeight_pos,
   ``ComputableAnalysis.normWeight_nonneg,
   ``ComputableAnalysis.sum_normWeight,
   ``ComputableAnalysis.sum_abs_normWeight_sub_le,
   -- The Bernstein integrand, uniformly in the word
   ``ComputableAnalysis.bernsteinBL_apply,
   ``ComputableAnalysis.integrandName_bernsteinName,
   ``ComputableAnalysis.primrec_bernsteinStreamFn,
   ``ComputableAnalysis.computableMap_bernsteinBL,
   ``ComputableAnalysis.monomialBL_apply,
   ``ComputableAnalysis.integrandName_monomialName,
   ``ComputableAnalysis.primrec_monomialStreamFn,
   ``ComputableAnalysis.monomialStreamFn_slice,
   -- From a moment name to a weak name
   ``ComputableAnalysis.dense_fracCode,
   ``ComputableAnalysis.primrec_momentPost,
   ``ComputableAnalysis.abs_momentApprox_sub_le,
   ``ComputableAnalysis.momentError_double_le,
   ``ComputableAnalysis.toMeasure_atomic_momentAtomList,
   ``ComputableAnalysis.levyProkhorovDist_atomic_momentAtomList_le,
   -- The computable Hausdorff moment theorem
   ``ComputableAnalysis.computableMap_momentsOfMeasure,
   ``ComputableAnalysis.computableMap_measureOfMoments,
   ``ComputableAnalysis.hausdorffMomentRep_equiv_weak,
   -- Problem algebra (issue #38)
   ``ComputableAnalysis.Problem.Tightens.refl,
   ``ComputableAnalysis.Problem.Tightens.trans,
   ``ComputableAnalysis.Problem.Tightens.antisymm,
   ``ComputableAnalysis.Problem.equivalent_iff_mutual_tightens,
   ``ComputableAnalysis.Problem.restrict_dom_iff,
   ``ComputableAnalysis.Problem.corestrict_dom_iff,
   ``ComputableAnalysis.Problem.tightens_restrict,
   ``ComputableAnalysis.Problem.corestrict_tightens_restrict,
   ``ComputableAnalysis.Problem.relThen_dom_iff,
   ``ComputableAnalysis.Problem.then_dom_iff,
   ``ComputableAnalysis.Problem.then_accepts_iff_of_safe,
   ``ComputableAnalysis.Problem.relThen_tightens_then,
   ``ComputableAnalysis.Problem.relThen_assoc,
   ``ComputableAnalysis.Problem.then_assoc,
   ``ComputableAnalysis.Problem.prod_dom_iff,
   ``ComputableAnalysis.Problem.coprod_dom_inl_iff,
   ``ComputableAnalysis.Problem.coprod_dom_inr_iff,
   ``ComputableAnalysis.Problem.Equivalent.prod,
   ``ComputableAnalysis.Problem.Equivalent.coprod,
   ``ComputableAnalysis.Problem.Tightens.prod,
   ``ComputableAnalysis.Problem.Tightens.coprod,
   ``ComputableAnalysis.Problem.Tightens.realizes,
   ``ComputableAnalysis.Problem.Realizes.«then»,
   -- Parallel product witnesses, cylinders, and the upgrade theorem (issue #28)
   ``ComputableAnalysis.IsStrongReductionPair.prod,
   ``ComputableAnalysis.IsReductionPair.prod,
   ``ComputableAnalysis.StrongWeihrauchReduction.prod_pre,
   ``ComputableAnalysis.StrongWeihrauchReduction.prod_post,
   ``ComputableAnalysis.WeihrauchReduction.prod_pre,
   ``ComputableAnalysis.WeihrauchReduction.prod_post,
   ``ComputableAnalysis.StrongWeihrauchReducible.prod,
   ``ComputableAnalysis.WeihrauchReducible.prod,
   ``ComputableAnalysis.IsCylinder,
   ``ComputableAnalysis.IsReductionPair.toProdId,
   ``ComputableAnalysis.WeihrauchReducible.strong_le_prod_id,
   ``ComputableAnalysis.IsCylinder.weihrauch_iff_strong,
   -- Lim is a cylinder (issue #28)
   ``ComputableAnalysis.OracleCode.eval_limCylIndexCode,
   ``ComputableAnalysis.OracleCode.evalStream_limCylPreCode,
   ``ComputableAnalysis.Lim.isCylinder,
   -- Countable parallelization and its closure laws (issue #29)
   ``ComputableAnalysis.Problem.parallelize_accepts_iff,
   ``ComputableAnalysis.Problem.parallelize_dom_iff,
   ``ComputableAnalysis.Problem.Equivalent.parallelize,
   ``ComputableAnalysis.IsStrongReductionPair.parallelize,
   ``ComputableAnalysis.IsReductionPair.parallelize,
   ``ComputableAnalysis.StrongWeihrauchReduction.parallelize_pre,
   ``ComputableAnalysis.StrongWeihrauchReduction.parallelize_post,
   ``ComputableAnalysis.WeihrauchReduction.parallelize_pre,
   ``ComputableAnalysis.WeihrauchReduction.parallelize_post,
   ``ComputableAnalysis.StrongWeihrauchReducible.parallelize,
   ``ComputableAnalysis.WeihrauchReducible.parallelize,
   ``ComputableAnalysis.parallelize_congr,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_extensive,
   ``ComputableAnalysis.parallelize_extensive,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_flatten,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_unflatten,
   ``ComputableAnalysis.parallelize_idempotent,
   ``ComputableAnalysis.IsParallelizable,
   ``ComputableAnalysis.IsStronglyParallelizable,
   ``ComputableAnalysis.IsStronglyParallelizable.isParallelizable,
   -- Arithmetic kit extension (issue #30)
   ``ComputableAnalysis.OracleCode.eval_predCode,
   ``ComputableAnalysis.OracleCode.eval_subCode,
   -- The calibration parallelize LPO ≡sW Lim (issue #30)
   ``ComputableAnalysis.stabFamily_track_allZero_iff,
   ``ComputableAnalysis.eval_limStabCode,
   ``ComputableAnalysis.evalStream_limStabCode,
   ``ComputableAnalysis.limFromBitsCode,
   ``ComputableAnalysis.isStrongReductionPair_lim_le_parallelize_lpo,
   ``ComputableAnalysis.lim_le_parallelize_lpo,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_lim,
   ``ComputableAnalysis.Lim.isStronglyParallelizable,
   ``ComputableAnalysis.parallelize_lpo_le_lim,
   ``ComputableAnalysis.parallelize_lpo_equiv_lim,
   -- Uniform reduction compilers (issue #31)
   ``ComputableAnalysis.BitConsistent,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_lpo_of_questions,
   ``ComputableAnalysis.sigma1Family_le_parallelize_lpo,
   ``ComputableAnalysis.isStrongReductionPair_lim_of_table,
   ``ComputableAnalysis.stabilizationTable_le_lim,
   ``ComputableAnalysis.sigma1Family_le_lim,
   -- The parallelized-LLPO compiler and its promise layer (issues #31, #32)
   ``ComputableAnalysis.firstOccurrenceFlags_ne_zero,
   ``ComputableAnalysis.firstOccurrenceFlags_atMostOne,
   ``ComputableAnalysis.not_event_of_track_zero,
   ``ComputableAnalysis.llpo_dom_of_atMostOne,
   ``ComputableAnalysis.flagFamily_le_parallelize_llpo,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_llpo_of_flags,
   -- Closed choice on two points and C₂ ≡sW LLPO (issue #32)
   ``ComputableAnalysis.C₂,
   ``ComputableAnalysis.C₂.accepts_iff,
   ``ComputableAnalysis.LLPO.accepts_iff,
   ``ComputableAnalysis.eval_llpoRemovalCode,
   ``ComputableAnalysis.isStrongReductionPair_llpo_le_c2,
   ``ComputableAnalysis.llpo_le_c2,
   ``ComputableAnalysis.c2FlagStream_even_zero_iff,
   ``ComputableAnalysis.c2FlagStream_odd_zero_iff,
   ``ComputableAnalysis.exists_c2FlagCode,
   ``ComputableAnalysis.mem_evalStream_c2FlagCode,
   ``ComputableAnalysis.isStrongReductionPair_c2_le_llpo,
   ``ComputableAnalysis.c2_le_llpo,
   ``ComputableAnalysis.c2_equiv_llpo,
   -- The binary-tree presentation of weak Kőnig's lemma (issue #32)
   ``ComputableAnalysis.treeWordDecode_treeWordCode,
   ``ComputableAnalysis.primrec_treeWordCode,
   ``ComputableAnalysis.primrec_treeWordDecode,
   ``ComputableAnalysis.WKL,
   ``ComputableAnalysis.WKL.accepts_iff,
   ``ComputableAnalysis.exists_path_of_isInfiniteTree,
   ``ComputableAnalysis.WKL.dom_iff,
   ``ComputableAnalysis.treeMemB_streamTake,
   ``ComputableAnalysis.treeMemB_streamTake_iff,
   ``ComputableAnalysis.primrec_treeMemB,
   -- The strict death race: WKL against parallelized LLPO (issue #32)
   ``ComputableAnalysis.AliveAt.mono,
   ``ComputableAnalysis.not_raceEvent_both,
   ``ComputableAnalysis.raceFlags_atMostOne,
   ``ComputableAnalysis.raceFlags_llpo_dom,
   ``ComputableAnalysis.infAbove_select,
   ``ComputableAnalysis.streamTake_pathStream,
   ``ComputableAnalysis.cantorRep_names_pathName,
   ``ComputableAnalysis.infAbove_pathWord,
   ``ComputableAnalysis.treeWordCode_lt_raceBound,
   ``ComputableAnalysis.mem_raceWords,
   ``ComputableAnalysis.aliveB_iff,
   ``ComputableAnalysis.raceEventB_iff,
   ``ComputableAnalysis.raceFlagB_eq,
   ``ComputableAnalysis.exists_raceFlagsCode,
   ``ComputableAnalysis.mem_evalStream_raceFlagsCode,
   ``ComputableAnalysis.pair_treeWordCode_lt_pathBound,
   ``ComputableAnalysis.pathWordOf_eq,
   ``ComputableAnalysis.exists_pathCode,
   ``ComputableAnalysis.mem_evalStream_pathCode,
   ``ComputableAnalysis.isStrongReductionPair_wkl_le_parallelize_llpo,
   ``ComputableAnalysis.wkl_le_parallelize_llpo,
   -- Closed choice on Cantor space, from negative information (issue #32)
   ``ComputableAnalysis.cantorForbiddenWord_eq_none_iff,
   ``ComputableAnalysis.cantorForbiddenWord_of_eq_code,
   ``ComputableAnalysis.isOpen_cantorForbiddenOpen,
   ``ComputableAnalysis.closedCantorSet_eq_compl,
   ``ComputableAnalysis.isClosed_closedCantorSet,
   ``ComputableAnalysis.closedCantorSet_congr,
   ``ComputableAnalysis.closedCantorSet_zero,
   ``ComputableAnalysis.C_Cantor,
   ``ComputableAnalysis.C_Cantor.accepts_iff,
   ``ComputableAnalysis.C_Cantor.dom_iff,
   -- WKL as negative information: the canonical-reindexed strong reduction (issue #32)
   ``ComputableAnalysis.treeForbiddenName,
   ``ComputableAnalysis.cantorForbiddenWord_treeForbiddenName,
   ``ComputableAnalysis.closedCantorSet_treeForbiddenName,
   ``ComputableAnalysis.c_Cantor_dom_treeForbiddenName,
   ``ComputableAnalysis.exists_treeForbiddenCode,
   ``ComputableAnalysis.mem_evalStream_treeForbiddenCode,
   ``ComputableAnalysis.isStrongReductionPair_wkl_le_c_cantor,
   ``ComputableAnalysis.wkl_le_c_cantor,
   -- and the converse: the length-staged tree, giving the presentation bridge (issue #32)
   ``ComputableAnalysis.cantorForbiddenWord_eq_some_iff,
   ``ComputableAnalysis.cantorForbiddenWord_congr,
   ``ComputableAnalysis.StagedTreeMem,
   ``ComputableAnalysis.closedCantorTreeMemB_iff,
   ``ComputableAnalysis.closedCantorTreeName,
   ``ComputableAnalysis.treeMem_closedCantorTreeName,
   ``ComputableAnalysis.isPrefixClosed_closedCantorTreeName,
   ``ComputableAnalysis.isInfiniteTree_closedCantorTreeName,
   ``ComputableAnalysis.paths_closedCantorTreeName,
   ``ComputableAnalysis.wkl_dom_closedCantorTreeName,
   ``ComputableAnalysis.exists_closedCantorTreeCode,
   ``ComputableAnalysis.mem_evalStream_closedCantorTreeCode,
   ``ComputableAnalysis.isStrongReductionPair_c_cantor_le_wkl,
   ``ComputableAnalysis.c_cantor_le_wkl,
   ``ComputableAnalysis.wkl_equiv_c_cantor,
   -- parallel binary choice as a closed set, and the LLPO/WKL calibration (issue #32)
   ``ComputableAnalysis.c2ParallelForbiddenName,
   ``ComputableAnalysis.c2ParallelForbiddenName_ne_zero_iff,
   ``ComputableAnalysis.cantorForbiddenWord_c2ParallelForbiddenName,
   ``ComputableAnalysis.closedCantorSet_c2ParallelForbiddenName,
   ``ComputableAnalysis.c_Cantor_dom_c2ParallelForbiddenName,
   ``ComputableAnalysis.exists_c2ParallelForbiddenCode,
   ``ComputableAnalysis.mem_evalStream_c2ParallelForbiddenCode,
   ``ComputableAnalysis.eval_c2ParallelAnswerCode,
   ``ComputableAnalysis.mem_evalStream_c2ParallelAnswerCode,
   ``ComputableAnalysis.isStrongReductionPair_parallelize_c2_le_c_cantor,
   ``ComputableAnalysis.parallelize_c2_le_c_cantor,
   ``ComputableAnalysis.parallelize_llpo_equiv_wkl,
   -- WKL/EFILC uniform-reduction pilot (issue #27 payload): the represented EFILC
   -- problem, its domain anchor, and the two reductions with explicit pairs
   ``ComputableAnalysis.EFILC.dom_iff,
   ``ComputableAnalysis.exists_section_of_promises,
   ``ComputableAnalysis.efilcSystemName,
   ``ComputableAnalysis.efilcFiber_efilcSystemName,
   ``ComputableAnalysis.efilcBond_efilcSystemName,
   ``ComputableAnalysis.isStrongReductionPair_efilc_of_system,
   ``ComputableAnalysis.strongReduction_efilc_of_system,
   ``ComputableAnalysis.fibersNonempty_treeSystemName,
   ``ComputableAnalysis.bondsIntoFiber_treeSystemName,
   ``ComputableAnalysis.isStrongReductionPair_wkl_le_efilc,
   ``ComputableAnalysis.wkl_le_efilc,
   ``ComputableAnalysis.isReductionPair_efilc_le_wkl,
   ``ComputableAnalysis.efilc_le_wkl,
   -- Hall pilot: the one-sided relation-plus-enumerator Hall problem, its domain anchor,
   -- and the strong reduction to EFILC
   ``ComputableAnalysis.Hall.dom_iff,
   ``ComputableAnalysis.fibersNonempty_hallSystemName,
   ``ComputableAnalysis.bondsIntoFiber_hallSystemName,
   ``ComputableAnalysis.isStrongReductionPair_hall_le_efilc,
   ``ComputableAnalysis.hall_le_efilc,
   -- The composite calibrations the interchange layer names
   ``ComputableAnalysis.efilc_equiv_wkl,
   ``ComputableAnalysis.hall_le_wkl,
   -- API consolidation (issue #49): principle semantics, packed sequence names,
   -- parallelizability accessors
   ``ComputableAnalysis.LPO.accepts_iff,
   ``ComputableAnalysis.LLPO.accepts_iff,
   ``ComputableAnalysis.Lim.accepts_iff,
   ``ComputableAnalysis.take_streamTake,
   ``ComputableAnalysis.Baire.track_packTracks,
   ``ComputableAnalysis.Representation.sequence_names_packTracks_iff,
   ``ComputableAnalysis.baireSequence_names_iff,
   ``ComputableAnalysis.natSequence_names_iff,
   ``ComputableAnalysis.IsParallelizable.collapse,
   ``ComputableAnalysis.IsStronglyParallelizable.collapse,
   ``ComputableAnalysis.isParallelizable_iff,
   ``ComputableAnalysis.isStronglyParallelizable_iff,
   ``ComputableAnalysis.parallelize_congr_strong]

#eval show CoreM Unit from do
  for t in headlineDecls do
    let axs ← collectAxioms t
    for a in axs do
      unless allowedAxioms.contains a do
        throwError "axiom audit: {t} depends on disallowed axiom {a}"
  let env ← getEnv
  let moduleNames := env.allImportedModuleNames
  let mut swept := 0
  for (name, _) in env.constants.toList do
    if let some idx := env.getModuleIdxFor? name then
      if (`ComputableAnalysis).isPrefixOf moduleNames[idx.toNat]! then
        let axs ← collectAxioms name
        for a in axs do
          unless allowedAxioms.contains a do
            throwError "axiom audit (sweep): {name} depends on disallowed axiom {a}"
        swept := swept + 1
  IO.println
    s!"axiom audit: {headlineDecls.length} headline declaration(s) clean; swept {swept}"
